version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:10.15.0

jobs:
  nodejs:
    executor: nodejs
    resource_class: small
    steps:
      - checkout:
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run: npm install --no-save
      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ checksum "package-lock.json" }}
      - run: npm test

workflows:
  version: 2
  thanos:
    jobs:
      - nodejs
