version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout:
      - restore_cache:
          keys:
            - node-v1-test-{{ checksum "package-lock.json" }}
      - run: npm install --no-save
      - save_cache:
          paths:
            - node_modules
          key: node-v1-test-{{ checksum "package-lock.json" }}
      - run: npm test
workflows:
  version: 2
  thanos:
    jobs:
      - test
